services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres
volumes:
  db:
    driver: local